# Generated by Django 5.1.11 on 2025-06-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_email_author_name_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
