# Generated by Django 5.1.11 on 2025-06-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='username',
        ),
    ]
