# Generated by Django 5.1.11 on 2025-06-29 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_rename_user_author_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAdmin',
            fields=[
                ('reporter', models.OneToOneField(default='', max_length=30, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=100)),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
    ]
