# Generated by Django 5.2.3 on 2025-06-29 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_remove_latestnews_slug_contactsubmission_slug'),
        ('users', '0005_itadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITAdmin',
            new_name='Profile',
        ),
    ]
