# Generated by Django 5.2.3 on 2025-06-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_itadmin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reporter',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
