# Generated by Django 5.2.3 on 2025-06-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_alter_newsreport_options_and_more'),
        ('users', '0007_alter_profile_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
