# Generated by Django 5.2.3 on 2025-07-04 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('title', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=500)),
                ('photo', models.ImageField(default='busgate.jpg', upload_to='media/photo')),
                ('is_approved', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='users.author')),
            ],
        ),
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('headline', models.TextField(default='', max_length=100, primary_key=True, serialize=False)),
                ('todaysDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='media/photo')),
                ('is_approved', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
