# Generated by Django 5.2.3 on 2025-06-29 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_itadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('title', models.CharField(default='', max_length=80, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=500)),
                ('photo', models.ImageField(default='busgate.jpg', upload_to='media/photo')),
                ('is_approved', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=25, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='users.itadmin')),
            ],
        ),
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('headline', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('todaysDate', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=500)),
                ('photo', models.ImageField(default='busgate.jpg', upload_to='media/photo')),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
