# Generated by Django 5.2.3 on 2025-06-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='slug',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True),
        ),
    ]
