# Generated by Django 5.2.3 on 2025-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_remove_latestnews_slug_contactsubmission_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreport',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='todaysDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
