# Generated by Django 5.2.3 on 2025-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_alter_newsreport_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestnews',
            options={'get_latest_by': 'Date'},
        ),
        migrations.AlterModelOptions(
            name='newsreport',
            options={'get_latest_by': 'todaysDate'},
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='slug',
        ),
        migrations.AddField(
            model_name='latestnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newsreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
