# Generated by Django 5.2.3 on 2025-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_alter_latestnews_options_alter_newsreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
