# Generated by Django 5.2.3 on 2025-06-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_alter_latestnews_slug_alter_newsreport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
