# Generated by Django 5.2.3 on 2025-06-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_alter_latestnews_slug_alter_newsreport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='headline',
            field=models.TextField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
