# Generated by Django 5.2.3 on 2025-06-30 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_alter_newsreport_author_alter_newsreport_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsreport',
            options={},
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='photo',
            field=models.ImageField(default='', upload_to='media/photo'),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
