# Generated by Django 5.2.3 on 2025-06-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_alter_newsreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestnews',
            options={},
        ),
    ]
