# Generated by Django 5.2.3 on 2025-07-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_alter_latestnews_options'),
        ('users', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreport',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.author'),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
