# Generated by Django 5.2.3 on 2025-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0011_alter_newsreport_author_alter_newsreport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
